apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: demo2
    function: test2
  name: demo2
  namespace: default
spec:
  replicas: 3
  selector:
    app: demo2
    function: test2
  template:
    metadata:
      labels:
        app: demo2
        function: test2
        version: v0.1
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: antmoveh/norm:latest
        imagePullPolicy: Always
        name: demo2
        ports:
        - containerPort: 8008
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        internet: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always