apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: demo
    function: test
  name: demo
  namespace: default
spec:
  replicas: 3
  selector:
    app: demo
    function: test
  template:
    metadata:
      labels:
        app: demo
        function: test
        version: v0.1
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: antmoveh/norm:latest
        imagePullPolicy: IfNotPresent
        name: demo
        ports:
        - containerPort: 8008
          protocol: TCP
        resources:
          limits:
            cpu: "0.2"
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always