apiVersion: v1
kind: Service
metadata:
  name: demo-server2
  namespace: default
  annotations:
    traefik.backend.circuitbreaker: "LatencyAtQuantileMS(50.0) > 50"
spec:
  selector:
    app: demo2
    function: test2
  ports:
  - name: web
    port: 80
    targetPort: 8008